services:
  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: embarkx
      POSTGRES_PASSWORD: embarkx
      POSTGRES_DB: postgres
      PG_DATA: /DATA/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/DATA/postgres
    networks:
      - postgres
    restart: unless-stopped
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_SERVER_MODE: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge